name: Pack .crx

on:
  release:
    types: [created]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  pack:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Read package.json
        id: package-version
        uses: martinbeentjes/npm-get-version-action@main
      - name: Build
        run: |
          npm ci
          npm run build
      - name: Pack .zip
        uses: cardinalby/webext-buildtools-pack-extension-dir-action@v1
        with:
          extensionDir: 'dist'
          zipFilePath: 'wai-v${{ steps.package-version.outputs.current-version }}.zip'
      - name: Pack .crx
        uses: cardinalby/webext-buildtools-chrome-crx-action@v2
        with:
          zipFilePath: 'wai-v${{ steps.package-version.outputs.current-version }}.zip'
          crxFilePath: 'wai-v${{ steps.package-version.outputs.current-version }}.crx'
          privateKey: ${{ secrets.CRX_PRIVATE_KEY }}
      - name: Update GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: 'v${{ steps.package-version.outputs.current-version }}'
          generate_release_notes: false
          files: |
            wai-v${{ steps.package-version.outputs.current-version }}.zip
            wai-v${{ steps.package-version.outputs.current-version }}.crx
